export const GENERATE_PASSWORD = 'GENERATE_PASSWORD';
export const SLIDER_CHANGE = 'SLIDER_CHANGE';

export const CHANGE_PASSWORD_STRONG = 'CHANGE_PASSWORD_STRONG'

export const CHANGE_CONFIGURATION_PASSWORD = 'CHANGE_CONFIGURATION_PASSWORD';
