import type { AppProps } from 'next/app'
import { PasswordThemeProvider } from "@password/core/theme/PasswordThemeProvider";
import {GlobalStyles} from "@password/core/theme/GlobalStyles";
import Head from "next/head";
import {PasswordContextProvider} from "@password/features/miguel-jardinez/password-generator/password-context/context/PasswordContextProvider";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Password generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="/fonts/fonts.css"/>
        <link rel="icon" href="/images/favicon.png" />
      </Head>
      <GlobalStyles />
      <PasswordContextProvider>
        <PasswordThemeProvider>
          <Component {...pageProps} />
        </PasswordThemeProvider>
      </PasswordContextProvider>
    </>
  )
}
